name: CI - MLflow Training & Docker

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Python
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          pip install mlflow==2.19.0 scikit-learn==1.5.2 pandas numpy matplotlib dagshub

      # 4. Run MLflow Project (training)
      - name: Run MLflow Project
        env:
          DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          mlflow run MLProject --env-manager=local

      # 5. Upload artefak ke GitHub
      - name: Upload artifacts to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: |
            confusion_matrix.png
            feature_importance.png
            roc_curve.png
            classification_report.txt

      # 6. Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 7. Login Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 8. Build & Push Docker image dari DagsHub artifact
      - name: Build and Push Docker image
        env:
          DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
          MLFLOW_TRACKING_URI: https://dagshub.com/notsaltt/Eksperimen1.mlflow
          MLFLOW_TRACKING_USERNAME: notsaltt
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          # Ambil run_id terbaru dari DagsHub via mlflow
          RUN_ID=$(python -c "
          import mlflow
          import os
          mlflow.set_tracking_uri(os.environ['MLFLOW_TRACKING_URI'])
          client = mlflow.tracking.MlflowClient()
          runs = client.search_runs(
              experiment_ids=['0'],
              order_by=['start_time DESC'],
              max_results=1
          )
          print(runs[0].info.run_id)
          ")
          echo "Latest Run ID: $RUN_ID"

          mlflow models build-docker \
            --model-uri "runs:/$RUN_ID/random_forest_model" \
            --name "${{ secrets.DOCKER_USERNAME }}/iris-mlflow:latest" \
            --env-manager local

          docker push ${{ secrets.DOCKER_USERNAME }}/iris-mlflow:latest